  import Head from 'next/head';
import Image from 'next/image';



export function Home() {
  return (
    <div >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      

      <main>
        <p className="text-4xl text-red-300">hello</p>
      </main>
    </div>
  );
}
