import Head from "next/head";
import axios from "axios";
import Image from "next/image";
import Card from "./Card";
import { useEffect, useState } from "react";

const url = "https://course-api.com/react-tours-project";

export function Home() {
   //set tours data
   const [tours, setTours] = useState([]);
   console.log(tours);

   useEffect(() => {
      const getData = async () => {
         try {
            const res = await axios.get(url);
            setTours(res.data);
         } catch (error) {
           console.log(error);
         }
      }
      getData();
   },[]);

   return (
      <div>
         <Head>
            <title>World of Warcraft Realty</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
         </Head>

         <main>
            <Card />
         </main>
      </div>
   );
}

//TODO:

