import Head from "next/head";
import axios from "axios";
import CardList from "./CardList";
import NoTours from "./NoTours";

import { css } from "@emotion/react"; //needed for the BarLoader
import BarLoader from "react-spinners/BarLoader"; //BarLoader component

import { useEffect, useState } from "react";

const url = "https://course-api.com/react-tours-project";

export function Home() {
   //set tours data and pass to cardList
   const [tours, setTours] = useState([]);
   const [loading, setLoading] = useState(false);

   const deleteTours = (id) => {
      const newTours = tours.filter((tour) => {
         return tour.id !== id;
      });
      setTours(newTours);
   };

   const getData = async () => {
      setLoading(true);
      try {
         const res = await axios.get(url);
         setTours(res.data);
         setLoading(false);
      } catch (error) {
         console.log(error);
         setLoading(false);
      }
   };

   useEffect(() => {
      getData();
   }, []);
   

   //used for BarLoader component
   const loaderCss = css`
      display: block;
   `;
   //if loading do this
   if (loading) {
      return (
         <main className="main">
            <BarLoader loading={loading} height={10} width={200} color="#93C5FD" css={loaderCss} />
         </main>
      );
   }

   //if no more tours do this
   if (tours.length === 0) {
     return (
        <main className='main'>
           <NoTours getData={getData}/>
        </main>
     )
   }

   return (
      <div>
         <Head>
            <title>Tours Inc</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
         </Head>

         <main className="main">
            <CardList tours={tours} deleteTours={deleteTours} />
         </main>
      </div>
   );
}


